# ---------------------------------------------------------------------------
# Default Configuration for UMUD Muscle Architecture Ultrasound Challenge
# ---------------------------------------------------------------------------
